[supervisord]
nodaemon=true
user=root

[program:vnc]
command=gosu ubuntu /opt/TurboVNC/bin/vncserver :0 -fg -wm xfce4-session -geometry 1366x667 -depth 24
autorestart=true
stderr_logfile=/var/log/supervisor/vnc.err.log
stdout_logfile=/var/log/supervisor/vnc.out.log

[program:novnc]
command=gosu ubuntu bash -c "websockify --web=/usr/lib/novnc 3000 localhost:5900"
autorestart=true
stderr_logfile=/var/log/supervisor/novnc.err.log
stdout_logfile=/var/log/supervisor/novnc.out.log

[program:windows-10]
command=/usr/bin/windows-10
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/var/log/windows-10.log
stderr_logfile=/var/log/windows-10.err
